dado = input('Digite algo: ')
print('O dado infomado é do tipo {}' . format(type(dado)))
print('O dado informado é alfabetico? -> {}' .format(dado.isalpha()))
print('O dado informado é alfanumerico? -> {}' .format(dado.isalnum()))
print('O dado informado é um numero? -> {}' .format(dado.isnumeric()))
print('O dado informado está apenas em letras maiuscula? -> {}' .format(dado.isupper()))
print('O dado informado está apenas em letras minuscula? -> {}' .format(dado.islower()))
print('O dado informado contém apenas espaços? -> {}' .format(dado.isspace()))
print('O dado informado está capitalizado? -> {}' .format(dado.istitle()))
